name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kunitoki/android-ndk-r21
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Android NDK
      run: echo "y" | ${ANDROID_HOME}/tools/bin/sdkmanager --install 'ndk;21.0.6113669' > /dev/null 2>&1
    - name: Install build system dependencies
      run: |
        apt-get update
        apt-get install -y gfortran mesa-common-dev libglfw3-dev clang
    - name: Build for Linux
      run: |
        DO_CLEAR=OFF BUILD_VISUALIZATIONS=OFF ./scripts/build.sh
    - name: Build for Android
      run: |
        BUILD_VISUALIZATIONS=OFF BUILD_EIGEN=OFF ./scripts/android/build.sh
    - name: Package (Debug)
      run: |
        ./scripts/package.sh
        mv build/mobile-cv-suite.tar.gz build/mobile-cv-suite-debug.tar.gz
    - uses: actions/upload-artifact@v2
      with:
        name: debug
        path: |
          build/mobile-cv-suite-debug.tar.gz
    - name: Package (Release)
      run: |
        rm -rf build/android
        mv build/android-release build/android
        ./scripts/package.sh
    - uses: actions/upload-artifact@v2
      with:
        name: release
        path: |
          build/mobile-cv-suite.tar.gz
