name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Android NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install 'ndk;21.0.6113669' > /dev/null 2>&1
    - name: Install GFortran
      run: |
        sudo apt-get update
        sudo apt-get install gfortran
    - name: Build for Linux
      run: |
        DO_CLEAR=OFF BUILD_VISUALIZATIONS=OFF ./scripts/build.sh
    - name: Build for Android
      run: |
        BUILD_VISUALIZATIONS=OFF BUILD_EIGEN=OFF ./scripts/android/build.sh
    - name: Package
      run: ./scripts/package.sh
    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          build/mobile-cv-suite.tar.gz
