name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install GFortran
      run: |
        sudo apt-get update
        sudo apt-get install gfortran
    - name: Build for Linux
      run: |
        DO_CLEAR=OFF BUILD_VISUALIZATIONS=OFF ./scripts/build.sh
    - name: Build for Android
      run: |
        DO_CLEAR=OFF BUILD_VISUALIZATIONS=OFF ./scripts/android/build.sh
